<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Author;
use App\Models\Story;

class StoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $stories = [
            [
                'title' => "Once upon a sunny day",
                'content' => "In Charles Dicken’s famous story, A Tale of Two Cities, the main characters are Sydney Carton and Michael De Montmorency. Michael De Montmorency is a young man who is a royalist and a friend to the King of France. He is also a prisoner in the days leading up to the French revolution. When he recounts his story to his friend Sydney Carton, he explains that he planned to save himself by killing himself at the end of it. Although this sounds crazy, it was his best option under the circumstances. In addition to explaining this plan, he also explains why it failed. In short, his life was saved by an unnamed lady. The beautiful brown fox jumped over the fence to escape the hunter’s hounds. At first glance, this may seem like an impossible task since foxes are not particularly light animals. However, they are excellent climbers due to their elongated toes and sharp claws. Furthermore, they can travel at high speeds on their powerful hind legs due to their long tails that act as balances for jumping purposes. Consequently, when the fox jumps over a fence, it does so quickly and easily without causing any damage to itself or its surroundings. On top of that, when it lands on its feet from its jump, it appears as though nothing has happened— there was no injury or damage that led up to its successful jump over the fence. The beautiful brown foxes were out of their natural habitats when humans began destroying their habitats for hunting dogs and sport dogs for fur production purposes. Consequently, many beautiful brown foxes had nowhere safe to go other than into traffic— which led them into danger once again as they tried to escape death on roads. In addition, hunting dogs were released into natural habitats after being trained by hunters who wanted them for hunting game animals such as deer and bear ursus (bears). Consequently, these hunting dogs were also driven by instinct to hunt down and kill beautiful brown foxes— resulting in them jumping over fences in order to escape these hunters’ hounds once again! Although all these factors might seem like they make no sense in retrospect— they actually did make perfect sense at the time since no one knew about animal psychology back then! Thanks to Benjamin Hart’s discovery of animal psychology 150 years ago — humans now know that animals have feelings just like people do! Next time you see a news report about animals behaving strangely or escaping death in dangerous ways, be sure not get discouraged! They are simply doing what comes naturally given their backgrounds— just like how one beautiful brown fox jumped over another beautiful brown fox’s grave!",
                'author_id' => "51",
                'publish_date'=> "1975-03-04",
                'imgURL' => "https://via.placeholder.com/640x480.png/000011?text=consequatur",
            ],
            [
                'title' => "Once upon a rainny day",
                'content' => "In Charles Dicken’s famous story, A Tale of Two Cities, the main characters are Sydney Carton and Michael De Montmorency. Michael De Montmorency is a young man who is a royalist and a friend to the King of France. He is also a prisoner in the days leading up to the French revolution. When he recounts his story to his friend Sydney Carton, he explains that he planned to save himself by killing himself at the end of it. Although this sounds crazy, it was his best option under the circumstances. In addition to explaining this plan, he also explains why it failed. In short, his life was saved by an unnamed lady. The beautiful brown fox jumped over the fence to escape the hunter’s hounds. At first glance, this may seem like an impossible task since foxes are not particularly light animals. However, they are excellent climbers due to their elongated toes and sharp claws. Furthermore, they can travel at high speeds on their powerful hind legs due to their long tails that act as balances for jumping purposes. Consequently, when the fox jumps over a fence, it does so quickly and easily without causing any damage to itself or its surroundings. On top of that, when it lands on its feet from its jump, it appears as though nothing has happened— there was no injury or damage that led up to its successful jump over the fence. The beautiful brown foxes were out of their natural habitats when humans began destroying their habitats for hunting dogs and sport dogs for fur production purposes. Consequently, many beautiful brown foxes had nowhere safe to go other than into traffic— which led them into danger once again as they tried to escape death on roads. In addition, hunting dogs were released into natural habitats after being trained by hunters who wanted them for hunting game animals such as deer and bear ursus (bears). Consequently, these hunting dogs were also driven by instinct to hunt down and kill beautiful brown foxes— resulting in them jumping over fences in order to escape these hunters’ hounds once again! Although all these factors might seem like they make no sense in retrospect— they actually did make perfect sense at the time since no one knew about animal psychology back then! Thanks to Benjamin Hart’s discovery of animal psychology 150 years ago — humans now know that animals have feelings just like people do! Next time you see a news report about animals behaving strangely or escaping death in dangerous ways, be sure not get discouraged! They are simply doing what comes naturally given their backgrounds— just like how one beautiful brown fox jumped over another beautiful brown fox’s grave!",
                'author_id' =>'51',
                'publish_date'=> "1975-01-15",
                'imgURL' => "https://via.placeholder.com/640x480.png/000011?text=consequatur",
            ],
            [
                'title' => "The endless chase",
                'content' => "Wile E. Coyote is known worldwide for his catch-and-chase methods. He uses a number of techniques to catch prey, including baiting traps, hunting in pairs, and using disguises. The humans' better technology and transport systems have made it easier for the coyote to catch prey. He first used this method in the film The Hunting Season, where he used a set of brass knuckles to capture a skunk. He also uses this method in the film The Roadrunner, where he uses a roadrunner whistle to lure the bird to him. These methods are effective because the humans' technology allows them to be wherever their prey is. The humans' transport systems allow them to quickly transport their food from one place to another. Wile E. Coyote's method of hunting in pairs is a good way to increase his chances of success. He can use his partner as a decoy to attract prey, while he chases and catches the prey. This method is effective because it allows him to quickly increase his number of kills. Wile E. Coyote also uses disguises to attract prey. He has used disguises as a roadrunner, a skunk, a bird, and a human. The humans' pollution has caused many extinctions, which has made it harder for the coyote to catch prey. When humans release harmful chemicals into the environment, they kill many species of animals. The coyote is one of these animals. The humans' pollution has impacted Wile E. Coyote's hunting methods by making it harder for him to catch prey. Many people believe that the humans' hunting methods have caused the death of many species, including the coyote. The humans have hunted and killed many species of animals, including the coyote. The humans' hunting methods have caused the death of many species, including the coyote. When humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans use the animals' body parts, the animals die a slow death from the damage caused by the human's use. In addition, the humans' hunting methods have also caused the death of many species, including the coyote. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans use the animals' body parts, the animals die a slow death from the damage caused by the human's use.",
                'author_id' =>'59',
                'publish_date'=> "1975-05-29",
                'imgURL' => "https://via.placeholder.com/640x480.png/000011?text=consequatur",
            ],
            [
                'title' => "Hunting again",
                'content' => "The humans' hunting methods have also caused the death of many species, including the coyote. The humans have killed the coyote for food or used their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts. When the humans hunt animals, they kill the animals for food or use their skins and other body parts.",
                'author_id' =>'52',
                'publish_date'=> "1975-06-10",
                'imgURL' => "https://via.placeholder.com/640x480.png/000011?text=consequatur",
            ],

        ];

        foreach($stories as $key => $value) {
            Story::create($value);
        }
    }
}
